### ISSUE TITLE
关于限位开关有个疑问？

### ISSUE THREAD

**Issue by liang872** [osnsyc/GrocyCompanionCN#1]
想知道限位开关的类型，是常开还是常闭的，另外限位开关按下的时候不是触发一下吗？怎么实现关停模块的功能呢？

**Comment by osnsyc** [comment]
三脚限位开关，常开常闭都是可以的设置的。使用常开模式，即不按常开、按下关闭。

安装在柜体内，用柜门关闭实现长按关停，柜门开启则开关复原（参考衣柜线灯的触发行为）。自由放置的话，适当增加一些配重，扫码侧面向桌面放置，自重可以让开关保持长按。

**Comment by liang872** [comment]
谢谢解惑～！

**Comment by hahaha3542** [comment]
> 想知道限位开关的类型，是常开还是常闭的，另外限位开关按下的时候不是触发一下吗？怎么实现关停模块的功能呢？

限位开关更常见的应该是触发保持模式吧就是按下去保持为触发，松开取消触发，那种按下触发一次的相对来说貌似还更少见一些1
