### ISSUE TITLE
商品条码未写入Grocy，且HTTP请求获得错误返回值

### ISSUE THREAD

**Issue by CINECUBE** [osnsyc/GrocyCompanionCN#7]
### GrocyCompanionCN Docker运行正常
<img width="397" alt="Snipaste_2024-04-06_01-51-01" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/44285248-a0fb-438b-bf36-b743509d9429">

### 使用“REQBIN”发送HTTP请求

`curl -X POST -H "Content-Type: application/json" -d '{"client":"temporary_storage","aimid":"]E0","barcode":"8935024140147"}' http://192.168.124.229:9288/add`

后返回：

#> `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`
> 
### REQBIN截图：
<img width="738" alt="Snipaste_2024-04-06_01-47-42" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/0e20e3fe-25bf-47e2-bdc1-e3d01abd8c2c">

### 但是 该物品的条码并没有被写入Grocy的对应物品中：
<img width="761" alt="Snipaste_2024-04-06_15-32-09" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/797accb0-df6a-4376-97be-6d75d0cb1647">

### Grocy Docker后台日志：

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "./app.py", line 147, in add
>     if add_product(good, client):
>   File "./app.py", line 54, in add_product
>     response_grocy = grocy.add_generic(EntityType.PRODUCTS, data_grocy)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 368, in add_generic
>     return self._api_client.add_generic(entity_type.value, data)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 783, in add_generic
>     return self._do_post_request(f"objects/{entity_type}", data)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 375, in _do_post_request
>     raise GrocyError(resp)
> pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:23:18] "POST /add HTTP/1.1" 500 -
> INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:23:44] "POST /add HTTP/1.1" 200 -
> ERROR:app:Exception on /add [POST]
> Traceback (most recent call last):
>   File "./app.py", line 136, in add
>     grocy.product_by_barcode(barcode)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 102, in product_by_barcode
>     resp = self._api_client.get_product_by_barcode(barcode)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 435, in get_product_by_barcode
>     parsed_json = self._do_get_request(url)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 358, in _do_get_request
>     raise GrocyError(resp)
> pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "./app.py", line 147, in add
>     if add_product(good, client):
>   File "./app.py", line 57, in add_product
>     grocy.set_userfields(
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 301, in set_userfields
>     return self._api_client.set_userfields(entity, object_id, key, value)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 705, in set_userfields
>     self._do_put_request(f"userfields/{entity}/{object_id}", data)
>   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 398, in _do_put_request
>     raise GrocyError(resp)
> pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:24:23] "POST /add HTTP/1.1" 500 -

### 提问：

1. 请问大佬这个返回的500 Internal Server Error“是正常的吗？
2. 我应该如何修改才能让商品条码同步写入至Grocy的对应商品中呢？

感谢！

**Comment by hahaha3542** [comment]
>"client":"temporary_storage"

建议确认下该字段的库存位置名称对应已存在的库存位置（注意字段须全小写）

**Comment by hahaha3542** [comment]
> ### 情况：
> ### GrocyCompanionCN Docker运行正常
> <img width="397" alt="Snipaste_2024-04-06_01-51-01" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/44285248-a0fb-438b-bf36-b743509d9429">
> 
> 
> ### 动作：
> ### 使用“REQBIN”发送HTTP请求
> 
> `curl -X POST -H "Content-Type: application/json" -d '{"client":"temporary_storage","aimid":"]E0","barcode":"8935024140147"}' http://192.168.124.229:9288/add`
> 
> 后返回：
> 
> #> `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> > <title>500 Internal Server Error</title>
> > <h1>Internal Server Error</h1>
> > <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`
> > 
> ### REQBIN截图：
> <img width="738" alt="Snipaste_2024-04-06_01-47-42" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/0e20e3fe-25bf-47e2-bdc1-e3d01abd8c2c">
> 
> ### 获得`500 Internal Server Error`返回值的同时：
> ### Grocy web产品列表内已经添加：**G7美式萃取黑咖啡**
> ### 但是 该物品的条码并没有被写入Grocy的对应物品中：
> <img width="761" alt="Snipaste_2024-04-06_15-32-09" src="https://github.com/osnsyc/GrocyCompanionCN/assets/64253420/797accb0-df6a-4376-97be-6d75d0cb1647">
> 
> 
> ### Grocy Docker后台日志：
> 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
> >     response = self.full_dispatch_request()
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
> >     rv = self.handle_user_exception(e)
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
> >     rv = self.dispatch_request()
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
> >     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> >   File "./app.py", line 147, in add
> >     if add_product(good, client):
> >   File "./app.py", line 54, in add_product
> >     response_grocy = grocy.add_generic(EntityType.PRODUCTS, data_grocy)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 368, in add_generic
> >     return self._api_client.add_generic(entity_type.value, data)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 783, in add_generic
> >     return self._do_post_request(f"objects/{entity_type}", data)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 375, in _do_post_request
> >     raise GrocyError(resp)
> > pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> > INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:23:18] "POST /add HTTP/1.1" 500 -
> > INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:23:44] "POST /add HTTP/1.1" 200 -
> > ERROR:app:Exception on /add [POST]
> > Traceback (most recent call last):
> >   File "./app.py", line 136, in add
> >     grocy.product_by_barcode(barcode)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 102, in product_by_barcode
> >     resp = self._api_client.get_product_by_barcode(barcode)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 435, in get_product_by_barcode
> >     parsed_json = self._do_get_request(url)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 358, in _do_get_request
> >     raise GrocyError(resp)
> > pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
> >     response = self.full_dispatch_request()
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
> >     rv = self.handle_user_exception(e)
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
> >     rv = self.dispatch_request()
> >   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
> >     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> >   File "./app.py", line 147, in add
> >     if add_product(good, client):
> >   File "./app.py", line 57, in add_product
> >     grocy.set_userfields(
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 301, in set_userfields
> >     return self._api_client.set_userfields(entity, object_id, key, value)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 705, in set_userfields
> >     self._do_put_request(f"userfields/{entity}/{object_id}", data)
> >   File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 398, in _do_put_request
> >     raise GrocyError(resp)
> > pygrocy.errors.grocy_error.GrocyError: <Response [400]>
> > INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 07:24:23] "POST /add HTTP/1.1" 500 -
> 
> ### 提问：
> 
> 1. 请问大佬这个返回的500 Internal Server Error“是正常的吗？
> 2. 我应该如何修改才能让商品条码同步写入至Grocy的对应商品中呢？
> 
> 感谢！
> 
> 

如果为Windows客户端建议直接用浏览器访问该网址以获取存储位置信息

>http://EXAMPLE.COM:PORT/api/objects/locations

**Comment by CINECUBE** [comment]
### 我重装了一次Grocy docker (IP已改为：http://192.168.124.8:9283)。
### 进行了以下动作：

1. 创建新用户
2. 修改语言
3. 增加新位置`temporary`（全小写）
4. 新增API key
5. 查询locations返回：

```
[
  {
    "id": 2,
    "name": "temporary",
    "description": null,
    "row_created_timestamp": "2024-04-06 20:15:00",
    "is_freezer": 0,
    "active": 1
  }
]
```

6.查询quantity_units返回：
```
[
  {
    "id": 2,
    "name": "Piece",
    "description": null,
    "row_created_timestamp": "2024-04-06 20:15:00",
    "name_plural": "Pieces",
    "plural_forms": null,
    "active": 1
  },
  {
    "id": 3,
    "name": "Pack",
    "description": null,
    "row_created_timestamp": "2024-04-06 20:15:00",
    "name_plural": "Packs",
    "plural_forms": null,
    "active": 1
  }
]
```

7.修改GrocyCompanionCN的config.ini文件如下：

```
[Grocy]
GROCY_URL = http://192.168.124.8
GROCY_PORT = 9283
GROCY_API = ******

GROCY_DEFAULT_QUANTITY_UNIT_ID = 2
GROCY_DEFAULT_BEST_BEFORE_DAYS = 365

[GrocyLocation]
temporary = 2

[RapidAPI]
X_RapidAPI_Key = ******
```

8.浏览器访问[192.168.124.8:9288](url)显示：

> GrocyCNCompanion Started!

9.依原提问，使用REQBIN发送HTTP请求：

`curl -X POST -H "Content-Type: application/json" -d '{"client":"temporary","aimid":"]E0","barcode":"8935024140147"}' http://192.168.124.8:9288/add`

仍然返回：
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
### 同时，Grocy web产品列表内出现新条目：G7美式萃取黑咖啡
但是 该物品的条码并没有被写入Grocy的对应物品中。



grocycompanioncn-spider-1 Docker日志：

```
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://172.22.0.2:9288/ (Press CTRL+C to quit)
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 12:53:52] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /add [POST]
Traceback (most recent call last):
  File "./app.py", line 136, in add
    grocy.product_by_barcode(barcode)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 102, in product_by_barcode
    resp = self._api_client.get_product_by_barcode(barcode)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 435, in get_product_by_barcode
    parsed_json = self._do_get_request(url)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 358, in _do_get_request
    raise GrocyError(resp)
pygrocy.errors.grocy_error.GrocyError: <Response [400]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./app.py", line 147, in add
    if add_product(good, client):
  File "./app.py", line 54, in add_product
    response_grocy = grocy.add_generic(EntityType.PRODUCTS, data_grocy)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy.py", line 368, in add_generic
    return self._api_client.add_generic(entity_type.value, data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 783, in add_generic
    return self._do_post_request(f"objects/{entity_type}", data)
  File "/usr/local/lib/python3.8/site-packages/pygrocy/grocy_api_client.py", line 375, in _do_post_request
    raise GrocyError(resp)
pygrocy.errors.grocy_error.GrocyError: <Response [400]>
INFO:werkzeug:192.168.124.240 - - [06/Apr/2024 12:54:03] "POST /add HTTP/1.1" 500 -
```

**Comment by hahaha3542** [comment]
日志显示了你的关键词依然设置错误，不清楚是否为误报。

>KeyError: 'temporary_storage'

而且查看了操作流程后发现你的Grocy主程序中少创建一个参数，参见快速开始强调部分第三条

`管理主数据`- `自定义字段`- 添加- 表单信息:实体:products;名称GDSInfo;标题:GDSInfo;类型:单行文本,勾选"在表格中显示此列"

**Comment by CINECUBE** [comment]
> 日志显示了你的关键词依然设置错误，不清楚是否为误报。
> 
> > KeyError: 'temporary_storage'
> 
> 而且查看了操作流程后发现你的Grocy主程序中少创建一个参数，参见快速开始强调部分第三条
> 
> `管理主数据`- `自定义字段`- 添加- 表单信息:实体:products;名称GDSInfo;标题:GDSInfo;类型:单行文本,勾选"在表格中显示此列"

感谢大神回复，确实是我忘记自定义字段**GDSInfo**。
通过完成动作：
`管理主数据- 自定义字段- 添加- 表单信息:实体:products;名称GDSInfo;标题:GDSInfo;类型:单行文本,勾选"在表格中显示此列"`
后，已取得正确的返回内容：

```
{
    "message": "New item added successfully"
}
```
